name: Build APK
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v2

        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
